// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prisma.Models;

namespace Prisma.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prisma.Models.Competidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calle");

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<decimal>("Latitud");

                    b.Property<decimal>("Longitud");

                    b.Property<int>("MarcaId");

                    b.Property<bool>("Marcador");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<bool>("Observar");

                    b.Property<int>("ZonaPrecioId");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ZonaPrecioId");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("Prisma.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "CF",
                            Nombre = "Carrefour"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CFE",
                            Nombre = "Carrefour Express"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "CO",
                            Nombre = "Coto"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "VEA",
                            Nombre = "Vea"
                        });
                });

            modelBuilder.Entity("Prisma.Models.ZonaPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ZonaPrecios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "N",
                            Nombre = "Norte"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "S",
                            Nombre = "Sur"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "E",
                            Nombre = "Este"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "O",
                            Nombre = "Oeste"
                        });
                });

            modelBuilder.Entity("Prisma.Models.Competidor", b =>
                {
                    b.HasOne("Prisma.Models.Marca", "Marca")
                        .WithMany("Competidores")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Prisma.Models.ZonaPrecio", "ZonaPrecio")
                        .WithMany("Competidores")
                        .HasForeignKey("ZonaPrecioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
